services:
  - type: web
    name: instaloaderbot
    env: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: instaloaderbot
          property: serviceDetails.url
